apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.wordpressDeploy.name }}
  labels:
{{- include "wordpress.deploy.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.wordpressDeploy.replicaCount }}
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:{{ .Values.wordpressDeploy.imageTag }}
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: WORDPRESS_DB_USER
              value: root
            - name: WORDPRESS_DB_NAME
              value: mysql
          ports:
            - containerPort: {{ .Values.wordpressDeploy.containerPort }}
              name: wordpress
          volumeMounts:
            - name: wp-volume
              mountPath: /var/www/html
      volumes:
        - name: wp-volume
          persistentVolumeClaim:
            claimName: {{ .Values.wordpressDeploy.pvcName }}
